routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Front\PageController@index')->name('home');

Route::get('404', function(){
    abort(404);
});
Route::get('404', function(){
    abort(500);
});
Route::get('errors', function () {
    return view('errors.list');
});
Auth::routes();
Route::prefix('admin')->group(function () {


    Route::get('', 'Admin\DashboardController@index')->name('dashboard');


    Route::prefix('users')->group(function () {
        Route::get('/data', 'Admin\UserController@data')->name('users.data');
        Route::get('/{user}/delete', 'Admin\UserController@destroy')->name('users.delete');
    });
    Route::resource('users', 'Admin\UserController');

    Route::prefix('menus')->group(function () {
        Route::get('/', 'Admin\MenuController@index')->name('menus');
        Route::post('/add-page', 'Admin\MenuController@addPage')->name('haddpagemmenu');

    });


    Route::prefix('pages')->group(function () {
        Route::get('/data', 'Admin\PageController@data')->name('pages.data');
        Route::get('/grapesjs', 'Admin\PageController@getGrapesJs')->name('pages.grapesjs');
        Route::post('/grapesjs/store', 'Admin\PageController@storeGrapesJs')->name('pages.store-grapesjs');
        Route::get('/{page}/delete', 'Admin\PageController@destroy')->name('pages.delete');
        Route::get('/{page}/content/edit', 'Admin\PageController@editContent')->name('pages.edit-content');
        Route::get('/{page}/content/add', 'Admin\PageController@addContent')->name('pages.add-content');
        Route::post('/{page}/content/add', 'Admin\PageController@storeContent')->name('pages.store-content');
        Route::post('/{page}/content/edit', 'Admin\PageController@updateContent')->name('pages.update-content');

    });
    Route::resource('pages', 'Admin\PageController');

    Route::prefix('templates')->group(function () {
        Route::post('/add-content-block', 'Admin\TemplateController@addContentBlock')->name('templates.add-content-block');///AJAX
        Route::get('/data', 'Admin\TemplateController@data')->name('templates.data');
        Route::get('/{template}/delete', 'Admin\TemplateController@destroy')->name('templates.delete');
        Route::get('/{ContentTemplate}/remove/', 'Admin\TemplateController@removeContentBlock')->name('templates.remove-block');
        Route::post('/sortContent', 'Admin\TemplateController@sortContent')->name('templates.sort-content');
    });
    Route::resource('templates', 'Admin\TemplateController');

    Route::prefix('image-uploader')->group(function () {
        Route::get('/data', 'Admin\ImageController@data')->name('image-uploader.data');
        Route::get('/{image}/delete', 'Admin\ImageController@destroy')->name('image-uploader.delete');
        Route::get('/picture-manager/', 'Admin\ImageController@selectImage')->name('images.picture-manager');
        Route::post('/add-image', 'Admin\ImageController@addImage')->name('images.add-image');
        Route::post('/process-sizes', 'Admin\ImageController@processSizes')->name('images.process-sizes');
        Route::post('/save-crop', 'Admin\ImageController@saveCrop')->name('images.saveCrop');
        Route::post('/upload', 'Admin\ImageController@upload')->name('images.upload');

    });
    Route::resource('image-uploader', 'Admin\ImageController');

    Route::prefix('tags')->group(function () {
        Route::get('/data', 'Admin\TagController@data')->name('tags.data');
        Route::get('/{tag}/delete', 'Admin\TagController@destroy')->name('tags.delete');
    });
    Route::resource('tags', 'Admin\TagController');

    Route::prefix('image-sizes')->group(function () {
        Route::get('/{imageSize}/delete', 'Admin\ImageSizeController@destroy')->name('image-sizes.delete');
    });
    Route::resource('image-sizes', 'Admin\ImageSizeController');

    Route::prefix('blocks')->group(function () {
        Route::get('/data', 'Admin\BlockController@data')->name('blocks.data');
        Route::get('/{block}/delete', 'Admin\BlockController@destroy')->name('blocks.delete');
    });
    Route::resource('blocks', 'Admin\BlockController');

    Route::prefix('content')->group(function () {
        Route::get('/data', 'Admin\ContentController@data')->name('content.data');
        Route::get('/{content}/delete', 'Admin\ContentController@destroy')->name('content.delete');
    });
    Route::resource('content', 'Admin\ContentController');

    Route::prefix('slideshows')->group(function () {
        Route::get('/data', 'Admin\SlideshowController@data')->name('slideshows.data');
        Route::get('/{slideshow}/delete', 'Admin\SlideshowController@destroy')->name('slideshows.delete');
        Route::get('/{slideshow}/add-slides', 'Admin\SlideshowController@addSlides')->name('slideshows.add-slides');
        Route::post('/store-slides', 'Admin\SlideshowController@storeSlides')->name('slideshows.store-slides');
        Route::get('/{slide}/delete-slide', 'Admin\SlideshowController@deleteSlide')->name('slideshows.delete-slide');
        Route::post('/sortSlides', 'Admin\SlideshowController@sortSlides')->name('slideshows.sort-slides');
    });

    Route::resource('slideshows', 'Admin\SlideshowController');

    Route::prefix('permissions')->group(function () {
        Route::get('/data', 'Admin\PermissionController@data')->name('permissions.data');
        Route::get('/{permission}/delete', 'Admin\PermissionController@destroy')->name('permissions.delete');
    });

    Route::resource('permissions', 'Admin\PermissionController');

    Route::prefix('roles')->group(function () {
        Route::get('/data', 'Admin\RoleController@data')->name('roles.data');
        Route::get('/{role}/delete', 'Admin\RoleController@destroy')->name('roles.delete');
    });

    Route::resource('roles', 'Admin\RoleController');

    Route::prefix('applications')->group(function () {
        Route::get('/data', 'Admin\ApplicationController@data')->name('applications.data');
        Route::get('/{application}/delete', 'Admin\ApplicationController@destroy')->name('applications.delete');
        Route::get('/{application}/note', 'Admin\ApplicationController@createNote')->name('applications.note');
        Route::post('/{application}/note', 'Admin\ApplicationController@storeNote');
        Route::get('/note/{applicationNote}/delete', 'Admin\ApplicationController@deleteNote')->name('applications.note.delete');
        Route::get('/note/{applicationNote}', 'Admin\ApplicationController@editNote')->name('applications.note.edit');
        Route::put('/note/{applicationNote}', 'Admin\ApplicationController@updateNote')->name('applications.note.update');
        Route::get('/{application}/pdf','Admin\ApplicationController@printPDF')->name('applications.pdf');
    });

    Route::resource('applications', 'Admin\ApplicationController');

    Route::prefix('contacts')->group(function () {
        Route::get('/data', 'Admin\ContactController@data')->name('contacts.data');
        Route::get('/{contact}/delete', 'Admin\ContactController@destroy')->name('contacts.delete');
    });

    Route::resource('contacts', 'Admin\ContactController');

    Route::prefix('faqs')->group(function () {
        Route::get('/data', 'Admin\FaqController@data')->name('faqs.data');
        Route::get('/{faq}/delete', 'Admin\FaqController@destroy')->name('faqs.delete');
    });

    Route::resource('faqs', 'Admin\FaqController');

    Route::prefix('documents')->group(function () {
//        Route::get('/data', 'Admin\FaqController@data')->name('faqs.data');
        Route::get('/{document}/delete', 'Admin\DocumentController@destroy')->name('documents.delete');
    });
    Route::resource('documents', 'Admin\DocumentController');

    Route::prefix('jobs-admin')->group(function () {
        Route::get('/data', 'Admin\JobController@data')->name('jobs-admin.data');
        Route::get('/{job}/delete', 'Admin\JobController@destroy')->name('jobs-admin.delete');

    });
    Route::resource('jobs-admin', 'Admin\JobController');

    Route::prefix('job-applications')->group(function () {
        Route::get('/data', 'Admin\JobApplicationController@data')->name('job-applications.data');
        Route::get('/{jobApplication}/delete', 'Admin\JobApplicationController@destroy')->name('job-applications.delete');
        Route::get('/{jobApplication}/note', 'Admin\JobApplicationController@createNote')->name('job-applications.note');
        Route::post('/{jobApplication}/note', 'Admin\JobApplicationController@storeNote');
        Route::get('/note/{jobApplicationNote}/delete', 'Admin\JobApplicationController@deleteNote')->name('job-applications.note.delete');
        Route::get('/note/{jobApplicationNote}', 'Admin\JobApplicationController@editNote')->name('job-applications.note.edit');
        Route::put('/note/{jobApplicationNote}', 'Admin\JobApplicationController@updateNote')->name('job-applications.note.update');
        Route::get('/{jobApplication}/pdf','Admin\JobApplicationController@printPDF')->name('job-applications.pdf');

    });
    Route::resource('job-applications', 'Admin\JobApplicationController');

    Route::prefix('appeals')->group(function () {
        Route::get('/data', 'Admin\AppealController@data')->name('appeals.data');
    });
    Route::resource('appeals', 'Admin\AppealController');

    Route::prefix('api')->group(function () {
        Route::get('/data', 'Admin\EvergivingAPIController@data')->name('api.data');
        Route::get('/{evergivingApi}/delete', 'Admin\EvergivingAPIController@destroy')->name('api.delete');
        Route::get('/test', 'Admin\EvergivingAPIController@test')->name('api.test');

    });

app/Application.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\SoftDeletes;

class Application extends Model
{
    use SoftDeletes;

    /**
     * @var array
     */
    protected $fillable = [
        'title',
        'first_name',
        'last_name',
        'order_name',
        'gender',
        'address',
        'postcode',
        'email',
        'mobile',
        'alt_tel'
    ];

    /**
     *
     */
    public static function boot() {
        parent::boot();

        //while creating/inserting item into db
        static::creating(function (Application $item) {
            if(Auth::user()) {
                $item->created_by = Auth::user()->id;
            } else {
                $item->created_by = 0;
            }
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function details()
    {
        return $this->hasOne('App\ApplicationDetail');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function appeals()
    {
        return $this->hasOne('App\ApplicationAppeal');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function references()
    {
        return $this->hasOne('App\ApplicationReferee');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function notes()
    {
        return $this->hasMany('App\ApplicationNote');
    }

    /**
     * Get all of the user's documents.
     */
    public function documents()
    {
        return $this->morphMany('App\Document', 'documentable');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function author()
    {
        return $this->belongsTo('App\User', 'created_by');
    }

}

app/Http/Controllers/Front/ApplicationController.php
<?php

namespace App\Http\Controllers\Front;

use App\ApplicationDetail;
use App\ApplicationReferee;
use App\Mail\ApplicationComplete;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Application;
use App\ApplicationAppeal;
use Harimayco\Menu\Facades\Menu;

use Illuminate\Support\Facades\Mail;


class ApplicationController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $menus = Menu::getByName('main_menu');
        return view('front.static.application', compact('menus'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function process(Request $request)
    {

        $this->validate($request, [
            'first_name'                    => 'required',
            'last_name'                     => 'required',
            'address'                       => 'required',
            'postcode'                      => 'required',
            'email'                         => 'required|email',
            'mobile'                        => 'required',
            'details.work_experience'       => 'required',
            'details.triratna_history'      => 'required',
            'appeals.type'                  => 'required',
            'appeals.season'                => 'required',
            'appeals.draw'                  => 'required',
            'appeals.skills'                => 'required',
            'appeals.difficulties'          => 'required',
            'details.health'                => 'required',
            'details.health_details'        => 'required_if:details[health], poor',
            'details.medication'            => 'required',
            'details.medication_details'    => 'required_if:details[medication],1',
            'details.safeguarding_offence'  => 'required',
            'details.criminal_offence'      => 'required',
            'details.offence_details'       => 'required_if:details[safeguarding_offence],1|required_if:details[criminal_offence],1',
            'reference.name_1'              => 'required',
            'reference.relationship_1'      => 'required',
            'reference.telephone_1'         => 'required',
            'reference.email_1'             => 'required|email',
            'reference.name_2'              => 'required',
            'reference.relationship_2'      => 'required',
            'reference.telephone_2'         => 'required',
            'reference.email_2'             => 'required|email',
            'details.support_package'      => 'required',
            'details.ethos'                 => 'required',
            'details.ethos_details'         => 'required_if:details[ethos],0',
            'details.privacy'               => 'required',
            'details.future_opportunities'  => 'required',
        ]);

        $application = $request->except('details','reference', 'appeals');
        $details = $request->only('details');
        $appeals = $request->only('appeals');
        $reference = $request->only('reference');


        $application = Application::create($application);

        $details['details']['application_id'] = $application->id;
        $details['details']['contact_source'] = implode(',', $details['details']['contact_source']);
        $appeals['appeals']['application_id'] = $application->id;
        $appeals['appeals']['type'] = implode(',', $appeals['appeals']['type']);
        $reference['reference']['application_id'] = $application->id;
        ApplicationDetail::create($details['details']);
        ApplicationAppeal::create($appeals['appeals']);
        ApplicationReferee::create($reference['reference']);

        Mail::to('rijusiddha@karuna.org')->send(new ApplicationComplete($application));

        $menus = Menu::getByName('main_menu');

        return view('front.static.thank-you', compact('menus'));
    }
}

resources/views/admin/applications/index.blade.php
@extends('admin.layouts.dashboard')

@section('content')

    <div class="box">
        <div class="box-header">
           Applications
        </div>

        <div class="box-content">
            <div class="table-responsive">
                <table class="table table-bordered table-striped" id="applications-table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Applicant</th>
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Applied</th>
                        <th></th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        $(function() {
            $.noConflict(true)
            $('#applications-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('applications.data')  }}',
                columns: [
                    { data: 'id', id: 'id' },
                    { data: 'name', name: 'name' },
                    { data: 'email', name: 'email' },
                    { data: 'mobile', name: 'mobile' },
                    { data: 'created_at', name: 'created_at' },
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
            });

        });

    </script>
@stop

resources/views/admin/applications/view.blade.php
@extends('admin.layouts.dashboard')

@section('content')

    <ul class="nav nav-tabs" id="application" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="true">Contact</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="details-tab" data-toggle="tab" href="#details" role="tab" aria-controls="details" aria-selected="false">Details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="appeals-tab" data-toggle="tab" href="#appeals" role="tab" aria-controls="appeals" aria-selected="false">Appeals</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="reference-tab" data-toggle="tab" href="#reference" role="tab" aria-controls="reference" aria-selected="false">Reference</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="documents-tab" data-toggle="tab" href="#documents" role="tab" aria-controls="documents" aria-selected="false">Documents</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="notes-tab" data-toggle="tab" href="#notes" role="tab" aria-controls="notes" aria-selected="false">Notes</a>
        </li>
    </ul>

    <div class="tab-content" id="applicationContent">
        @include('admin.applications.partials._contact')
        @include('admin.applications.partials._details')
        @include('admin.applications.partials._appeals')
        @include('admin.applications.partials._references')
        @include('admin.applications.partials._documents')
        @include('admin.applications.partials._notes')
    </div>


<div class="form-action clearfix">
    <div class="pull-right">
        <a href="{{ route('applications.index') }}" class="btn btn-secondary"><i class="fas fa-bars"></i> Back to list</a>
        @can('Edit Application')
            <a href="{{ route('applications.edit', $application->id) }}" class="btn btn-primary"><i class="fas fa-pencil-alt"></i>  Edit</a>
        @endcan
        @can('Add Application Note')
            <a href="{{ route('applications.note', $application->id) }}" class="btn btn-success"><i class="fas fa-paperclip"></i>  Add Note</a>
        @endcan
        <a href="{{route('applications.pdf', $application->id)}}" class="btn btn-secondary"><i class="fas fa-download"></i> Download and Print as PDF</a>
        @can('Add Document')
            <a href="{{ route('documents.create', ['model' => 'App\Application','application_id' => $application->id]) }}" class="btn btn-success"><i class="fas fa-file"></i>  Add Document</a>
        @endcan
        @can('Delete Application')
            <a href="{{ route('applications.delete', $application->id) }}" title="delete" class="btn btn-danger"><i class="fas fa-trash"></i>  Delete</a>
        @endcan
    </div>
</div>
@stop