routes/web.php
    Route::get('', 'Admin\DashboardController@index')->name('dashboard');


    Route::prefix('users')->group(function () {
        Route::get('/data', 'Admin\UserController@data')->name('users.data');
        Route::get('/{user}/delete', 'Admin\UserController@destroy')->name('users.delete');
    });
    Route::resource('users', 'Admin\UserController');

    Route::prefix('menus')->group(function () {
        Route::get('/', 'Admin\MenuController@index')->name('menus');
        Route::post('/add-page', 'Admin\MenuController@addPage')->name('haddpagemmenu');

    });


    Route::prefix('pages')->group(function () {
        Route::get('/data', 'Admin\PageController@data')->name('pages.data');
        Route::get('/grapesjs', 'Admin\PageController@getGrapesJs')->name('pages.grapesjs');
        Route::post('/grapesjs/store', 'Admin\PageController@storeGrapesJs')->name('pages.store-grapesjs');
        Route::get('/{page}/delete', 'Admin\PageController@destroy')->name('pages.delete');
        Route::get('/{page}/content/edit', 'Admin\PageController@editContent')->name('pages.edit-content');
        Route::get('/{page}/content/add', 'Admin\PageController@addContent')->name('pages.add-content');
        Route::post('/{page}/content/add', 'Admin\PageController@storeContent')->name('pages.store-content');
        Route::post('/{page}/content/edit', 'Admin\PageController@updateContent')->name('pages.update-content');

    });
    Route::resource('pages', 'Admin\PageController');

    Route::prefix('templates')->group(function () {
        Route::post('/add-content-block', 'Admin\TemplateController@addContentBlock')->name('templates.add-content-block');///AJAX
        Route::get('/data', 'Admin\TemplateController@data')->name('templates.data');
        Route::get('/{template}/delete', 'Admin\TemplateController@destroy')->name('templates.delete');
        Route::get('/{ContentTemplate}/remove/', 'Admin\TemplateController@removeContentBlock')->name('templates.remove-block');
        Route::post('/sortContent', 'Admin\TemplateController@sortContent')->name('templates.sort-content');
    });
    Route::resource('templates', 'Admin\TemplateController');

    Route::prefix('image-uploader')->group(function () {
        Route::get('/data', 'Admin\ImageController@data')->name('image-uploader.data');
        Route::get('/{image}/delete', 'Admin\ImageController@destroy')->name('image-uploader.delete');
        Route::get('/picture-manager/', 'Admin\ImageController@selectImage')->name('images.picture-manager');
        Route::post('/add-image', 'Admin\ImageController@addImage')->name('images.add-image');
        Route::post('/process-sizes', 'Admin\ImageController@processSizes')->name('images.process-sizes');
        Route::post('/save-crop', 'Admin\ImageController@saveCrop')->name('images.saveCrop');
        Route::post('/upload', 'Admin\ImageController@upload')->name('images.upload');

    });
    Route::resource('image-uploader', 'Admin\ImageController');

    Route::prefix('tags')->group(function () {
        Route::get('/data', 'Admin\TagController@data')->name('tags.data');
        Route::get('/{tag}/delete', 'Admin\TagController@destroy')->name('tags.delete');
    });
    Route::resource('tags', 'Admin\TagController');

    Route::prefix('image-sizes')->group(function () {
        Route::get('/{imageSize}/delete', 'Admin\ImageSizeController@destroy')->name('image-sizes.delete');
    });
    Route::resource('image-sizes', 'Admin\ImageSizeController');

    Route::prefix('blocks')->group(function () {
        Route::get('/data', 'Admin\BlockController@data')->name('blocks.data');
        Route::get('/{block}/delete', 'Admin\BlockController@destroy')->name('blocks.delete');
    });
    Route::resource('blocks', 'Admin\BlockController');

    Route::prefix('content')->group(function () {
        Route::get('/data', 'Admin\ContentController@data')->name('content.data');
        Route::get('/{content}/delete', 'Admin\ContentController@destroy')->name('content.delete');
    });
    Route::resource('content', 'Admin\ContentController');

    Route::prefix('slideshows')->group(function () {
        Route::get('/data', 'Admin\SlideshowController@data')->name('slideshows.data');
        Route::get('/{slideshow}/delete', 'Admin\SlideshowController@destroy')->name('slideshows.delete');
        Route::get('/{slideshow}/add-slides', 'Admin\SlideshowController@addSlides')->name('slideshows.add-slides');
        Route::post('/store-slides', 'Admin\SlideshowController@storeSlides')->name('slideshows.store-slides');
        Route::get('/{slide}/delete-slide', 'Admin\SlideshowController@deleteSlide')->name('slideshows.delete-slide');
        Route::post('/sortSlides', 'Admin\SlideshowController@sortSlides')->name('slideshows.sort-slides');
    });

    Route::resource('slideshows', 'Admin\SlideshowController');

    Route::prefix('permissions')->group(function () {
        Route::get('/data', 'Admin\PermissionController@data')->name('permissions.data');
        Route::get('/{permission}/delete', 'Admin\PermissionController@destroy')->name('permissions.delete');
    });

    Route::resource('permissions', 'Admin\PermissionController');

    Route::prefix('roles')->group(function () {
        Route::get('/data', 'Admin\RoleController@data')->name('roles.data');
        Route::get('/{role}/delete', 'Admin\RoleController@destroy')->name('roles.delete');
    });

    Route::resource('roles', 'Admin\RoleController');

    Route::prefix('applications')->group(function () {
        Route::get('/data', 'Admin\ApplicationController@data')->name('applications.data');
        Route::get('/{application}/delete', 'Admin\ApplicationController@destroy')->name('applications.delete');
        Route::get('/{application}/note', 'Admin\ApplicationController@createNote')->name('applications.note');
        Route::post('/{application}/note', 'Admin\ApplicationController@storeNote');
        Route::get('/note/{applicationNote}/delete', 'Admin\ApplicationController@deleteNote')->name('applications.note.delete');
        Route::get('/note/{applicationNote}', 'Admin\ApplicationController@editNote')->name('applications.note.edit');
        Route::put('/note/{applicationNote}', 'Admin\ApplicationController@updateNote')->name('applications.note.update');
        Route::get('/{application}/pdf','Admin\ApplicationController@printPDF')->name('applications.pdf');
    });

    Route::resource('applications', 'Admin\ApplicationController');

    Route::prefix('contacts')->group(function () {
        Route::get('/data', 'Admin\ContactController@data')->name('contacts.data');
        Route::get('/{contact}/delete', 'Admin\ContactController@destroy')->name('contacts.delete');
    });

    Route::resource('contacts', 'Admin\ContactController');

    Route::prefix('faqs')->group(function () {
        Route::get('/data', 'Admin\FaqController@data')->name('faqs.data');
        Route::get('/{faq}/delete', 'Admin\FaqController@destroy')->name('faqs.delete');
    });

    Route::resource('faqs', 'Admin\FaqController');

    Route::prefix('documents')->group(function () {
//        Route::get('/data', 'Admin\FaqController@data')->name('faqs.data');
        Route::get('/{document}/delete', 'Admin\DocumentController@destroy')->name('documents.delete');
    });
    Route::resource('documents', 'Admin\DocumentController');

    Route::prefix('jobs-admin')->group(function () {
        Route::get('/data', 'Admin\JobController@data')->name('jobs-admin.data');
        Route::get('/{job}/delete', 'Admin\JobController@destroy')->name('jobs-admin.delete');

    });
    Route::resource('jobs-admin', 'Admin\JobController');

    Route::prefix('job-applications')->group(function () {
        Route::get('/data', 'Admin\JobApplicationController@data')->name('job-applications.data');
        Route::get('/{jobApplication}/delete', 'Admin\JobApplicationController@destroy')->name('job-applications.delete');
        Route::get('/{jobApplication}/note', 'Admin\JobApplicationController@createNote')->name('job-applications.note');
        Route::post('/{jobApplication}/note', 'Admin\JobApplicationController@storeNote');
        Route::get('/note/{jobApplicationNote}/delete', 'Admin\JobApplicationController@deleteNote')->name('job-applications.note.delete');
        Route::get('/note/{jobApplicationNote}', 'Admin\JobApplicationController@editNote')->name('job-applications.note.edit');
        Route::put('/note/{jobApplicationNote}', 'Admin\JobApplicationController@updateNote')->name('job-applications.note.update');
        Route::get('/{jobApplication}/pdf','Admin\JobApplicationController@printPDF')->name('job-applications.pdf');

    });
    Route::resource('job-applications', 'Admin\JobApplicationController');

    Route::prefix('appeals')->group(function () {
        Route::get('/data', 'Admin\AppealController@data')->name('appeals.data');
    });
    Route::resource('appeals', 'Admin\AppealController');

    Route::prefix('api')->group(function () {
        Route::get('/data', 'Admin\EvergivingAPIController@data')->name('api.data');
        Route::get('/{evergivingApi}/delete', 'Admin\EvergivingAPIController@destroy')->name('api.delete');
        Route::get('/test', 'Admin\EvergivingAPIController@test')->name('api.test');

    });
    Route::resource('api', 'Admin\EvergivingAPIController');



});

// front routes
Route::get('/application', 'Front\ApplicationController@index')->name('application');
Route::post('/application', 'Front\ApplicationController@process')->name('process');
Route::get('/contact', 'Front\ContactController@index')->name('contact');
Route::post('/contact', 'Front\ContactController@process')->name('contact-process');
Route::get('/jobs', 'Front\JobController@index')->name('job');
Route::get('/jobs/application', 'Front\JobController@create')->name('job.apply');
Route::post('/jobs/application', 'Front\JobController@store')->name('job.process');

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Job extends Model
{
    use SoftDeletes;

    /**
     * @var string
     */
    protected $table = 'jobs';

    protected $fillable = [
        'title',
        'description',
        'caption',
        'closing_date'
    ];

    /**
     * @var array
     */
    protected $dates = [
        'closing_date'
    ];

    /**
     *
     */
    public static function boot() {
        parent::boot();

        //while creating/inserting item into db
        static::creating(function (Job $item) {

            $item->created_by = Auth::user()->id;
        });

    }
    /**
     * Get all of the user's documents.
     */
    public function documents()
    {
        return $this->morphMany('App\Document', 'documentable');
    }
}

app/Http/Controllers/Admin/JobController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Job;
use Carbon\Carbon;
use App\Document;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Auth;

class JobController extends Controller
{
    /**
     *  JobController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');

    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        Auth::user()->hasPermissionTo('View Job');
        $jobs = Job::all();

        return view('admin.jobs.index', compact('jobs'));
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function data(Request $request)
    {
        $jobs = Job::all();

        return Datatables::of($jobs)

            ->editColumn('closing_date', function($job){
                if(!empty($job->closing_date)){
                    return $job->closing_date->format('d/m/Y');
                }
                return 'No end date set';
            })

            ->addColumn('action', function ($job) {

                $menu = '<a data-toggle="tooltip" data-original-title="View" href="' . route('jobs-admin.show', $job->id) . '" class="tooltip-pivot pull-left"><i class="fa fa-eye"></i></a>';
                if(Auth::user()->hasPermissionTo('View Job Application')) {
                    $menu .= '<a data-toggle="tooltip" data-original-title="Applications" href="' .route('job-applications.index', ['job_id' => $job->id]).'" class="tooltip-pivot pull-left"><i class="fas fa-bars"></i></a>';
                }
                if(Auth::user()->hasPermissionTo('Edit Job')) {
                    $menu .= '<a data-toggle="tooltip" data-original-title="Edit" href="' .route('jobs-admin.edit', $job->id).'" class="tooltip-pivot pull-left"><i class="fas fa-pencil-alt "></i></a>';
                }
                if(Auth::user()->hasPermissionTo('Delete Job')) {
                    $menu .= '<a data-toggle="tooltip" data-original-title="Delete" href="'.route('jobs-admin.delete', $job->id).'" class="tooltip-pivot pull-left"><i class="fa fa-times"></i></a>';
                }
                return $menu;
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Auth::user()->hasPermissionTo('Add Job');

        return view('admin.jobs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Auth::user()->hasPermissionTo('Add Job');

        if(!empty($request['closing_date'])) {
            $request['closing_date'] = Carbon::createFromFormat('d-m-Y',$request['closing_date']);
        }

        $this->validate($request, [
                'title'         =>  'required',
                'caption'       =>  'required',
                'job_document'  =>  'mimes:pdf',

            ]
        );

        $job = Job::create($request->only('title', 'caption', 'description', 'closing_date'));

        //store document
        $document = $request->file('job_document')->getClientOriginalName();
        $path = $request->file('job_document')->store('public/documents');
        $docInput = [
            'original_filename' =>  $document,
            'filename'          =>  $path,
            'documentable_id'   =>  $job->id,
            'documentable_type' =>  'App\\Job',
            'created_by'        =>  Auth::user()->id
        ];

        Document::create($docInput);

        return redirect()->route('jobs-admin.show', $job)->with('flash_message',
            'Job Created!');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $job = Job::findOrFail($id);
        Auth::user()->hasPermissionTo('View Job');
        return view('admin.jobs.view', compact('job'));
    }


    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        Auth::user()->hasPermissionTo('Edit Job');

        $job = Job::findOrFail($id);
        return view('admin.jobs.edit', compact('job'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Auth::user()->hasPermissionTo('Edit Block');

        $job = Job::findOrFail($id);

        $request['closing_date'] = Carbon::createFromFormat('d/m/Y',$request['closing_date']);

        $this->validate($request, [
            'title'         =>  'required',
            'caption'       =>  'required',
            'closing_date'  =>  'required|date|after:tomorrow'

        ]);

        $input = $request->except('_token');

        $job->fill($input);
        $job->save();

        return redirect()->route('jobs-admin.show', $job)->with('flash_message', 'Job Updated!');
    }

    /**
     * @param $id
    * @return \Illuminate\Http\RedirectResponse
    * @throws \Exception
    */
    public function destroy($id)
    {
        Auth::user()->hasPermissionTo('Delete Job');
        $job = Job::findOrFail($id);
        if (isset($job)) {
            $job->delete();

            return redirect()->route('jobs-admin.index')
                ->with('flash_message',
                    'Job successfully deleted.');
        }

        return redirect()->route('jobs-admin.index')
            ->with('flash_message',
                'Cannot delete Job. Job not found');
    }
}

resources/views/admin/jobs/create.blade.php
@extends('admin.layouts.dashboard')

@section('content')
    {{ Form::open(['url' => 'admin/jobs-admin', 'enctype' => 'multipart/form-data', 'files' => true,])  }}
    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <div class="box-header">
                    Create New Job
                </div>
                <div class="box-content">
                    <div class="form-group">
                        {{ Form::label('title', 'Title')  }}
                        {{ Form::text('title', old('title'), ['class' => 'form-control'])  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('caption', 'Caption')  }}
                        {{ Form::text('caption', old('caption'), ['class' => 'form-control'])  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('closing_date', 'Closing Date')  }}
                        {{ Form::text('closing_date', old('closing_date'), ['class' => 'form-control datepicker'])  }}
                    </div>
                    <div class="alert-info">Only PDF versions can be uploaded</div>
                    <div class="form-group">
                        {{ Form::label('job_document', 'Job Document')  }}
                        {{ Form::file('job_document')  }}
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-content">
                    <div class="form-group">
                        {{ Form::label('description', 'Description')  }}
                        {{ Form::textarea('description', old('description'), ['class' => 'form-control editor'])  }}
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="form-action clearfix">
        <div class="pull-right">
            <a href="{{ route('jobs-admin.index') }}" class="btn btn-secondary"><i class="fas fa-list"></i> Back to list</a>
            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Create</button>
        </div>
    </div>

    {{ Form::close()  }}

@endsection

resources/views/admin/jobs/edit.blade.php
@extends('admin.layouts.dashboard')

@section('content')
    {{ Form::model($job, ['route' => ['jobs-admin.update', $job->id], 'method' => 'PUT'])  }}
    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <div class="box-header">
                    Job Details
                </div>
                <div class="box-content">
                    <div class="form-group">
                        {{ Form::label('title', 'Title')  }}
                        {{ Form::text('title', $job->title, ['class' => 'form-control'])  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('caption', 'Caption')  }}
                        {{ Form::text('caption', $job->caption, ['class' => 'form-control'])  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('closing_date', 'Closing Date')  }}
                        {{ Form::text('closing_date', $job->closing_date->format('d/m/Y'), ['class' => 'form-control datepicker'])  }}
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-content">
                    <div class="form-group">
                        {{ Form::label('description', 'Description')  }}
                        {{ Form::textarea('description', $job->description, ['class' => 'form-control editor'])  }}
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="form-action clearfix">
        <div class="pull-right">
            <a href="{{ route('jobs-admin.index') }}" class="btn btn-secondary"><i class="fas fa-list"></i> Back to list</a>
            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Update</button>
        </div>
    </div>

    {{ Form::close()  }}

@endsection

resources/views/admin/jobs/index.blade.php
@extends('admin.layouts.dashboard')

@section('content')

    <div class="box">
        <div class="box-header">
            <div class="box-buttons">
                <a href="{{ route('jobs-admin.create') }}" data-toggle="tooltip" title="" class="box-btn tooltip-pivot" data-original-title="Add"><i class="fas fa-plus"></i></a>
            </div>

            @if (isset($title))
                {{ $title  }}
            @else
                Jobs
            @endif

        </div>
        <div class="box-content">
            <table class="table table-bordered" id="jobs-table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Caption</th>
                    <th>Closing Date</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>

    <a class="btn btn-success pull-right" href="{{ route('jobs-admin.create')  }}" class="btn btn-success"><i class="fas fa-plus"></i> Add Job</a>

@stop

@section('scripts')
    <script>
        $(function() {
            $.noConflict(true)
            var oTable = $('#jobs-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '{{ route('jobs-admin.data')  }}'
                },
                order: [[ 1, "asc" ]],
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'title', name: 'title' },
                    { data: 'caption', name: 'caption' },
                    { data: 'closing_date', name: 'closing_date' },
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
            });

        });

    </script>
@stop

resources/views/admin/jobs/view.blade.php
@extends('admin.layouts.dashboard')

@section('content')

    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <div class="box-header">
                    Job Details
                </div>

                <div class="box-content">
                    <dl class="dl-horizontal">
                        <dt>Title</dt>
                        <dd>{{ $job->title }}</dd>
                        <dt>Caption</dt>
                        <dd>{{ $job->caption }}</dd>
                        <dt>Closing Date</dt>
                        <dd>{{ !empty($job->closing_date) ? $job->closing_date->format('d/m/Y') : 'No end date'}}</dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box">
                <div class="box-header">
                    Job Description
                </div>
                <div class="box-content">
                    <dl class="dl-horizontal">
                        <dt>Description</dt>
                        <dd>{!! $job->description !!}</dd>

                    </dl>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    Job Description Document
                </div>

                <div class="box-content">
                    <embed src="{{ asset('/images/'.$job->documents->first()->filename)  }}" width="100%" height="500px">
                </div>
            </div>
        </div>
    </div>
    <div class="form-action clearfix">
        <div class="pull-right">
            <a href="{{ route('jobs-admin.index') }}" class="btn btn-secondary"><i class="fas fa-bars"></i> Back to list</a>
            @can('Edit Job')
                <a href="{{ route('jobs-admin.edit', $job->id) }}" class="btn btn-primary"><i class="fas fa-pencil-alt "></i> Edit</a>
            @endcan
            @can('Delete Job')
                <a href="{{ route('jobs-admin.delete', $job->id) }}" title="delete" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a>
            @endcan
        </div>
    </div>
@stop