routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Front\PageController@index')->name('home');

Route::get('404', function(){
    abort(404);
});
Route::get('404', function(){
    abort(500);
});
Route::get('errors', function () {
    return view('errors.list');
});
Auth::routes();
Route::prefix('admin')->group(function () {


    Route::get('', 'Admin\DashboardController@index')->name('dashboard');


    Route::prefix('users')->group(function () {
        Route::get('/data', 'Admin\UserController@data')->name('users.data');
        Route::get('/{user}/delete', 'Admin\UserController@destroy')->name('users.delete');
    });
    Route::resource('users', 'Admin\UserController');

    Route::prefix('menus')->group(function () {
        Route::get('/', 'Admin\MenuController@index')->name('menus');
        Route::post('/add-page', 'Admin\MenuController@addPage')->name('haddpagemmenu');

    });


    Route::prefix('pages')->group(function () {
        Route::get('/data', 'Admin\PageController@data')->name('pages.data');
        Route::get('/grapesjs', 'Admin\PageController@getGrapesJs')->name('pages.grapesjs');
        Route::post('/grapesjs/store', 'Admin\PageController@storeGrapesJs')->name('pages.store-grapesjs');
        Route::get('/{page}/delete', 'Admin\PageController@destroy')->name('pages.delete');
        Route::get('/{page}/content/edit', 'Admin\PageController@editContent')->name('pages.edit-content');
        Route::get('/{page}/content/add', 'Admin\PageController@addContent')->name('pages.add-content');
        Route::post('/{page}/content/add', 'Admin\PageController@storeContent')->name('pages.store-content');
        Route::post('/{page}/content/edit', 'Admin\PageController@updateContent')->name('pages.update-content');

    });
    Route::resource('pages', 'Admin\PageController');

    Route::prefix('templates')->group(function () {
        Route::post('/add-content-block', 'Admin\TemplateController@addContentBlock')->name('templates.add-content-block');///AJAX
        Route::get('/data', 'Admin\TemplateController@data')->name('templates.data');
        Route::get('/{template}/delete', 'Admin\TemplateController@destroy')->name('templates.delete');
        Route::get('/{ContentTemplate}/remove/', 'Admin\TemplateController@removeContentBlock')->name('templates.remove-block');
        Route::post('/sortContent', 'Admin\TemplateController@sortContent')->name('templates.sort-content');
    });
    Route::resource('templates', 'Admin\TemplateController');

    Route::prefix('image-uploader')->group(function () {
        Route::get('/data', 'Admin\ImageController@data')->name('image-uploader.data');
        Route::get('/{image}/delete', 'Admin\ImageController@destroy')->name('image-uploader.delete');
        Route::get('/picture-manager/', 'Admin\ImageController@selectImage')->name('images.picture-manager');
        Route::post('/add-image', 'Admin\ImageController@addImage')->name('images.add-image');
        Route::post('/process-sizes', 'Admin\ImageController@processSizes')->name('images.process-sizes');
        Route::post('/save-crop', 'Admin\ImageController@saveCrop')->name('images.saveCrop');
        Route::post('/upload', 'Admin\ImageController@upload')->name('images.upload');

    });
    Route::resource('image-uploader', 'Admin\ImageController');

    Route::prefix('tags')->group(function () {
        Route::get('/data', 'Admin\TagController@data')->name('tags.data');
        Route::get('/{tag}/delete', 'Admin\TagController@destroy')->name('tags.delete');
    });
    Route::resource('tags', 'Admin\TagController');

    Route::prefix('image-sizes')->group(function () {
        Route::get('/{imageSize}/delete', 'Admin\ImageSizeController@destroy')->name('image-sizes.delete');
    });
    Route::resource('image-sizes', 'Admin\ImageSizeController');

    Route::prefix('blocks')->group(function () {
        Route::get('/data', 'Admin\BlockController@data')->name('blocks.data');
        Route::get('/{block}/delete', 'Admin\BlockController@destroy')->name('blocks.delete');
    });
    Route::resource('blocks', 'Admin\BlockController');

    Route::prefix('content')->group(function () {
        Route::get('/data', 'Admin\ContentController@data')->name('content.data');
        Route::get('/{content}/delete', 'Admin\ContentController@destroy')->name('content.delete');
    });
    Route::resource('content', 'Admin\ContentController');

    Route::prefix('slideshows')->group(function () {
        Route::get('/data', 'Admin\SlideshowController@data')->name('slideshows.data');
        Route::get('/{slideshow}/delete', 'Admin\SlideshowController@destroy')->name('slideshows.delete');
        Route::get('/{slideshow}/add-slides', 'Admin\SlideshowController@addSlides')->name('slideshows.add-slides');
        Route::post('/store-slides', 'Admin\SlideshowController@storeSlides')->name('slideshows.store-slides');
        Route::get('/{slide}/delete-slide', 'Admin\SlideshowController@deleteSlide')->name('slideshows.delete-slide');
        Route::post('/sortSlides', 'Admin\SlideshowController@sortSlides')->name('slideshows.sort-slides');
    });

    Route::resource('slideshows', 'Admin\SlideshowController');

    Route::prefix('permissions')->group(function () {
        Route::get('/data', 'Admin\PermissionController@data')->name('permissions.data');
        Route::get('/{permission}/delete', 'Admin\PermissionController@destroy')->name('permissions.delete');
    });

    Route::resource('permissions', 'Admin\PermissionController');

    Route::prefix('roles')->group(function () {
        Route::get('/data', 'Admin\RoleController@data')->name('roles.data');
        Route::get('/{role}/delete', 'Admin\RoleController@destroy')->name('roles.delete');
    });

    Route::resource('roles', 'Admin\RoleController');

    Route::prefix('applications')->group(function () {
        Route::get('/data', 'Admin\ApplicationController@data')->name('applications.data');
        Route::get('/{application}/delete', 'Admin\ApplicationController@destroy')->name('applications.delete');
        Route::get('/{application}/note', 'Admin\ApplicationController@createNote')->name('applications.note');
        Route::post('/{application}/note', 'Admin\ApplicationController@storeNote');
        Route::get('/note/{applicationNote}/delete', 'Admin\ApplicationController@deleteNote')->name('applications.note.delete');
        Route::get('/note/{applicationNote}', 'Admin\ApplicationController@editNote')->name('applications.note.edit');
        Route::put('/note/{applicationNote}', 'Admin\ApplicationController@updateNote')->name('applications.note.update');
        Route::get('/{application}/pdf','Admin\ApplicationController@printPDF')->name('applications.pdf');
    });

    Route::resource('applications', 'Admin\ApplicationController');

    Route::prefix('contacts')->group(function () {
        Route::get('/data', 'Admin\ContactController@data')->name('contacts.data');
        Route::get('/{contact}/delete', 'Admin\ContactController@destroy')->name('contacts.delete');
    });

    Route::resource('contacts', 'Admin\ContactController');

    Route::prefix('faqs')->group(function () {
        Route::get('/data', 'Admin\FaqController@data')->name('faqs.data');
        Route::get('/{faq}/delete', 'Admin\FaqController@destroy')->name('faqs.delete');
    });

    Route::resource('faqs', 'Admin\FaqController');

    Route::prefix('documents')->group(function () {
//        Route::get('/data', 'Admin\FaqController@data')->name('faqs.data');
        Route::get('/{document}/delete', 'Admin\DocumentController@destroy')->name('documents.delete');
    });
    Route::resource('documents', 'Admin\DocumentController');

    Route::prefix('jobs-admin')->group(function () {
        Route::get('/data', 'Admin\JobController@data')->name('jobs-admin.data');
        Route::get('/{job}/delete', 'Admin\JobController@destroy')->name('jobs-admin.delete');

    });
    Route::resource('jobs-admin', 'Admin\JobController');

    Route::prefix('job-applications')->group(function () {
        Route::get('/data', 'Admin\JobApplicationController@data')->name('job-applications.data');
        Route::get('/{jobApplication}/delete', 'Admin\JobApplicationController@destroy')->name('job-applications.delete');
        Route::get('/{jobApplication}/note', 'Admin\JobApplicationController@createNote')->name('job-applications.note');
        Route::post('/{jobApplication}/note', 'Admin\JobApplicationController@storeNote');
        Route::get('/note/{jobApplicationNote}/delete', 'Admin\JobApplicationController@deleteNote')->name('job-applications.note.delete');
        Route::get('/note/{jobApplicationNote}', 'Admin\JobApplicationController@editNote')->name('job-applications.note.edit');
        Route::put('/note/{jobApplicationNote}', 'Admin\JobApplicationController@updateNote')->name('job-applications.note.update');
        Route::get('/{jobApplication}/pdf','Admin\JobApplicationController@printPDF')->name('job-applications.pdf');

    });
    Route::resource('job-applications', 'Admin\JobApplicationController');

    Route::prefix('appeals')->group(function () {
        Route::get('/data', 'Admin\AppealController@data')->name('appeals.data');
    });
    Route::resource('appeals', 'Admin\AppealController');

    Route::prefix('api')->group(function () {
        Route::get('/data', 'Admin\EvergivingAPIController@data')->name('api.data');
        Route::get('/{evergivingApi}/delete', 'Admin\EvergivingAPIController@destroy')->name('api.delete');
        Route::get('/test', 'Admin\EvergivingAPIController@test')->name('api.test');

    });

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpKernel\EventListener\FragmentListener;

class Image extends Model
{
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'url',
        'name',
        'alt_tag',
        'title_tag'
    ];

    /**
     *
     */
    public static function boot() {
        parent::boot();

        //while creating/inserting item into db
        static::creating(function (Image $item) {

            $item->created_by = Auth::user()->id;
        });

    }

    /**
     * Get all of the images tags.
     */
    public function tags()
    {
        return $this->morphToMany('App\Tag', 'taggable');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function sizes()
    {
        return $this->belongsToMany('App\ImageSize', 'images_sizes_pivot', 'image_id', 'size_id');
    }

    /**
     * @param $columnWidth
     * @return Image[]|\Illuminate\Database\Eloquent\Collection|string
     */
    public static function getImageSizes($columnWidth)
    {
        switch ($columnWidth) {
            case $columnWidth == 12:
                $images = self::getImages(['Full Image']);
                break;
            case $columnWidth >=6 && $columnWidth <12;
                $images = self::getImages(['Large Landscape']);
                break;
            case $columnWidth >=3 && $columnWidth <6:
                $images = self::getImages(['Medium Landscape', 'Medium Square']);
                break;
            case $columnWidth <3:
                $images = self::getImages(['Small Landscape']);
                break;
            default:
                $images = "";
        }

        return($images);
    }

    /**
     * @param $size
     * @return Image[]|\Illuminate\Database\Eloquent\Collection
     */
    public static function getImages($size)
    {
        if($size) {
            $images = Image::join('images_sizes_pivot', 'images_sizes_pivot.image_id', '=', 'images.id')
                ->join('image_sizes', 'image_sizes.id', '=', 'images_sizes_pivot.size_id')
                ->where('image_sizes.size', $size)
                ->get();

            return $images;
        }

        $images = Image::all();

        return $images;
    }

    /**
     * @param $columnWidth
     * @param $imageName
     * @return string
     */
    public static function getImageSize($columnWidth, $imageName)
    {
        switch ($columnWidth) {
            case $columnWidth == 12:
                $image = 'full_image';
                break;
            case $columnWidth >=5 && $columnWidth <12;
                $image ='large_landscape';
                break;
            case $columnWidth >3 && $columnWidth <5:
                if (file_exists( public_path() . '/images/medium_landscape/'.$imageName . '')) {
                    $image = 'medium_landscape';
                } else {
                    $image = 'medium_square';
                }

                break;
            case $columnWidth <=3:
                $image = 'small_landscape';
                break;
            default:
                $image = "";
        }

        return $image;
    }
}

resources/views/admin/images/create.blade.php
@extends('admin.layouts.dashboard')

@section('content')

    {{ Form::open(['url' => 'admin/image-uploader', 'enctype' => 'multipart/form-data', 'files' => true, 'id' => 'image-form'])  }}
    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <div class="box-header">
                    Image Details
                </div>
                <div class="box-content">

                    <div class="form-group">
                        {{ Form::label('image', 'Image')  }}
                        {{ Form::file('image')  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('alt_tag', 'Alt Tag')  }}
                        {{ Form::text('alt_tag', old('alt_tag'), ['class' => 'form-control'])  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('title_tag', 'Title Tag')  }}
                        {{ Form::text('title_tag', old('title_tag'), ['class' => 'form-control'])  }}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box">
                <div class="box-header">
                    Extra Details
                </div>
                <div class="box-content">
                    <div class="form-group">
                        {{ Form::label('image-size', 'Image Size')  }}
                        {{ Form::select('image-size[]', $sizes, old('image-size[]'), ['class' => 'form-control selectpicker', 'id' => 'image-sizes', 'data-live-search' => 'true', 'multiple' => 'multiple'])  }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('tags', 'Tags')  }}
                        {{ Form::select('tags[]', $tags, old('tags[]'), ['class' => 'form-control selectpicker', 'id' => 'tags', 'data-live-search' => 'true', 'multiple' => 'multiple']) }}
                    </div>


                </div>
            </div>
        </div>
    </div>

    <div class="form-action clearfix">
        <div class="pull-right">
            <a href="" class="btn btn-success" id="get-sizes"><i class="fas fa-search-plus"></i> Get Sizes</a>
            <a href="{{ route('image-uploader.index')  }}" class="btn btn-secondary"><span data-feather="list"></span> Back to list</a>
        </div>
    </div>

@endsection

@section('scripts')
    <script>


        $('#get-sizes').click(function(e) {
            e.preventDefault();
            var form = new FormData(document.getElementById('image-form'));
            //append files
            var file = document.getElementById('image').files[0];
            if (file) {
                form.append('image', file);
            }
            $.ajax({
                /* the route pointing to the post function */
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: '{{ URL::route('images.process-sizes') }}',
                type: 'POST',
                async:false,
                data:form,
                dataType: 'html',
                processData: false,
                contentType:false,

                /* remind that 'data' is the response of the AjaxController */
                success: function (response) {
                    $('#main').append(response)
                    $('#get-sizes').replaceWith('<button type="submit" class="btn btn-primary"><span data-feather="edit"></span> Create</button>');

                    {{--$('#content-blocks').append('<div class="row"><div class="col-md-2 col-md-offset-10"><a href="{{ route('templates.remove-block', $block->id) }}" title="delete" class="btn btn-danger btn-template"><i "class="fas fa-trash"></i> Remove Content Block</a></div></div>')--}}

                },
                complete: function () {
                    if($('#croppic1').length) {
                        var image1 = $('.croppic1').attr('src');
                        var eyeCandy1 = $('#croppic1');
                        var croppicContainerPreloadOptions1 = {
                            cropUrl:'{{ url('admin/image-uploader/save-crop')}}',
                            cropData: {
                                '_token' : $('meta[name="csrf-token"]').attr('content'),
                                'width' : eyeCandy1.data('width'),
                                'height': eyeCandy1.data('height'),
                                'size'  : eyeCandy1.data('size')
                            },
                            loadPicture:image1,
                            enableMousescroll:true,

                            loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',

                        }
                        var cropContainerPreload1 = new Croppic('croppic1', croppicContainerPreloadOptions1);
                    }
                    if($('#croppic2').length) {
                        var image2 = $('.croppic2').attr('src');
                        var eyeCandy2 = $('#croppic2');
                        var croppicContainerPreloadOptions2 = {
                            cropUrl:'{{ url('admin/image-uploader/save-crop')}}',
                            cropData: {
                                '_token' : $('meta[name="csrf-token"]').attr('content'),
                                'width' : eyeCandy2.data('width'),
                                'height': eyeCandy2.data('height'),
                                'size'  : eyeCandy2.data('size')
                            },
                            loadPicture:image2,
                            enableMousescroll:true,

                            loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',

                        }

                        var cropContainerPreload2 = new Croppic('croppic2', croppicContainerPreloadOptions2);
                    }
                    if($('#croppic3').length) {
                        var image3 = $('.croppic3').attr('src');
                        var eyeCandy3 = $('#croppic3');
                        var croppicContainerPreloadOptions3 = {
                            cropUrl:'{{ url('admin/image-uploader/save-crop')}}',
                            cropData: {
                                '_token' : $('meta[name="csrf-token"]').attr('content'),
                                'width' : eyeCandy3.data('width'),
                                'height': eyeCandy3.data('height'),
                                'size'  : eyeCandy3.data('size')
                            },
                            loadPicture:image3,
                            enableMousescroll:true,

                            loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',

                        }

                        var cropContainerPreload3 = new Croppic('croppic3', croppicContainerPreloadOptions3);
                    }
                    if($('#croppic4').length) {
                        var image4 = $('.croppic4').attr('src');
                        var eyeCandy4 = $('#croppic4');
                        var croppicContainerPreloadOptions4= {
                            cropUrl:'{{ url('admin/image-uploader/save-crop')}}',
                            cropData: {
                                '_token' : $('meta[name="csrf-token"]').attr('content'),
                                'width' : eyeCandy4.data('width'),
                                'height': eyeCandy4.data('height'),
                                'size'  : eyeCandy4.data('size')
                            },
                            loadPicture:image4,
                            enableMousescroll:true,

                            loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',

                        }
                        var cropContainerPreload4 = new Croppic('croppic4', croppicContainerPreloadOptions4);
                    }
                    if($('#croppic5').length) {
                        var image5 = $('.croppic5').attr('src');
                        var eyeCandy5 = $('#croppic5');
                        var croppicContainerPreloadOptions5= {
                            cropUrl:'{{ url('admin/image-uploader/save-crop')}}',
                            cropData: {
                                '_token' : $('meta[name="csrf-token"]').attr('content'),
                                'width' : eyeCandy5.data('width'),
                                'height': eyeCandy5.data('height'),
                                'size'  : eyeCandy5.data('size')
                            },
                            loadPicture:image5,
                            enableMousescroll:true,

                            loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',

                        }
                        var cropContainerPreload5 = new Croppic('croppic5', croppicContainerPreloadOptions5);
                    }
                    if($('#croppic6').length) {
                        var image6 = $('.croppic6').attr('src');
                        var eyeCandy6 = $('#croppic6');
                        var croppicContainerPreloadOptions6= {
                            cropUrl:'{{ url('admin/image-uploader/save-crop')}}',
                            cropData: {
                                '_token' : $('meta[name="csrf-token"]').attr('content'),
                                'width' : eyeCandy6.data('width'),
                                'height': eyeCandy6.data('height'),
                                'size'  : eyeCandy6.data('size')
                            },
                            loadPicture:image6,
                            enableMousescroll:true,

                            loaderHtml:'<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',

                        }
                        var cropContainerPreload6 = new Croppic('croppic6', croppicContainerPreloadOptions6);
                    }
                }
            });
        });
    </script>
@stop

resources/views/admin/images/edit.blade.php
@extends('admin.layouts.dashboard')

@section('content')
    {{ Form::model($image, ['route' => ['image-uploader.update', $image->id], 'method' => 'PUT', 'enctype' => 'multipart/form-data'])  }}

    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <div class="box-header">
                    Image Detail - {{ $image->name }}
                </div>
                <div class="box-content">

                    <div class="form-group">
                        {{ Form::label('alt_tag', 'Alt Tag')  }}
                        {{ Form::text('alt_tag', $image->alt_tag, ['class' => 'form-control'])  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('title_tag', 'Title Tag')  }}
                        {{ Form::text('title_tag', $image->title_tag, ['class' => 'form-control'])  }}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box">
                <div class="box-header">
                    Extra Details
                </div>
                <div class="box-content">
                    <div class="form-group">
                        {{ Form::label('image-size', 'Image Size')  }}
                        {{ Form::select('image-size[]', $sizes, old('image-size[]'), ['class' => 'form-control selectpicker', 'data-live-search' => 'true', 'multiple' => 'multiple'])  }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('tags', 'Tags')  }}
                        {{ Form::select('tags[]', $tags, old('tags[]'), ['class' => 'form-control selectpicker', 'id' => 'tags', 'data-live-search' => 'true', 'multiple' => 'multiple']) }}
                    </div>


                </div>
            </div>
        </div>
    </div>
    <div class="form-action clearfix">
        <div class="pull-right">
            <a href="{{ route('image-uploader.index')  }}" class="btn btn-secondary"><span data-feather="list"></span> Back to list</a>
            <button type="submit" class="btn btn-primary"><span data-feather="edit"></span> Update</button>
        </div>
    </div>
    {{ Form::close()  }}
@endsection

resources/views/admin/images/view.blade.php
@extends('admin.layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <div class="box-header">
                    Image Details
                </div>

                <div class="box-content">
                    <dl class="dl-horizontal">
                        <dt>Name</dt>
                        <dd>{{ $image->name }}</dd>

                        <dt>Alt tag</dt>
                        <dd>{{ $image->alt_tag }}</dd>

                        <dt>Title tag</dt>
                        <dd>{{ $image->title_tag }}</dd>

                        <dt>Tags</dt>
                        <dd>{{ $image->title_tag }}</dd>

                    </dl>
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-md-12 tab-content">


            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="original-tab" data-toggle="tab" href="#original" role="tab" aria-controls="original" aria-selected="true">Original</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="thumb-tab" data-toggle="tab" href="#thumb" role="tab" aria-controls="thumb" aria-selected="false">Thumb</a>
                </li>
                @foreach($image->sizes as $size)
                    <li class="nav-item">
                        <a class="nav-link" id="{{ str_replace(' ','-', strtolower($size->size)) }}-tab" data-toggle="tab" href="#{{ str_replace(' ','-', strtolower($size->size)) }}" role="tab" aria-controls="{{ strtolower
                        ($size->size) }}"
                           aria-selected="false">{{
                        $size->size
                        }}</a>
                    </li>
                @endforeach

            </ul>
            <div class="box">
                <div class="box-content">
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane active" id="original" role="tabpanel" aria-labelledby="original-tab">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="box">
                                        <div class="box-content">
                                            <img src="/images/original/{{ $image->name }}" alt="{{ $image->alt_tag }}" title="{{ $image->title_tag }}" class="img-responsive"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="tab-pane" id="thumb" role="tabpanel" aria-labelledby="thumb-tab">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="box">
                                        <div class="box-content">
                                            <img src="/images/thumbs/{{ $image->name }}" alt="{{ $image->alt_tag }}" title="{{ $image->title_tag }}" class="img-responsive"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @foreach ($image->sizes as $size)
                            <div class="tab-pane" id="{{ str_replace(' ','-', strtolower($size->size)) }}" role="tabpanel" aria-labelledby="{{ str_replace(' ','-', strtolower($size->size)) }}-tab">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="box">
                                            <div class="box-content">
                                                <img src="/images/{{ str_replace(' ','_',strtolower($size->size)) }}/{{ $image->name }}" alt="{{ $image->alt_tag }}" title="{{ $image->title_tag }}" class="img-responsive"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-action clearfix">
        <div class="pull-right">
            <a href="{{ route('image-uploader.index') }}" class="btn btn-secondary"><i class="fas fa-bars"></i> Back to list</a>
            @can('Edit Image')
                <a href="{{ route('image-uploader.edit', $image->id) }}" class="btn btn-primary"><i class="fas fa-pencil-alt "></i> Edit</a>
            @endcan
            @can('Delete Image')
                <a href="{{ route('image-uploader.destroy', $image->id) }}" title="delete" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a>
            @endcan
        </div>
    </div>
@stop