routes/web.php
    Route::get('', 'Admin\DashboardController@index')->name('dashboard');


    Route::prefix('users')->group(function () {
        Route::get('/data', 'Admin\UserController@data')->name('users.data');
        Route::get('/{user}/delete', 'Admin\UserController@destroy')->name('users.delete');
    });
    Route::resource('users', 'Admin\UserController');

    Route::prefix('menus')->group(function () {
        Route::get('/', 'Admin\MenuController@index')->name('menus');
        Route::post('/add-page', 'Admin\MenuController@addPage')->name('haddpagemmenu');

    });


    Route::prefix('pages')->group(function () {
        Route::get('/data', 'Admin\PageController@data')->name('pages.data');
        Route::get('/grapesjs', 'Admin\PageController@getGrapesJs')->name('pages.grapesjs');
        Route::post('/grapesjs/store', 'Admin\PageController@storeGrapesJs')->name('pages.store-grapesjs');
        Route::get('/{page}/delete', 'Admin\PageController@destroy')->name('pages.delete');
        Route::get('/{page}/content/edit', 'Admin\PageController@editContent')->name('pages.edit-content');
        Route::get('/{page}/content/add', 'Admin\PageController@addContent')->name('pages.add-content');
        Route::post('/{page}/content/add', 'Admin\PageController@storeContent')->name('pages.store-content');
        Route::post('/{page}/content/edit', 'Admin\PageController@updateContent')->name('pages.update-content');

    });
    Route::resource('pages', 'Admin\PageController');

    Route::prefix('templates')->group(function () {
        Route::post('/add-content-block', 'Admin\TemplateController@addContentBlock')->name('templates.add-content-block');///AJAX
        Route::get('/data', 'Admin\TemplateController@data')->name('templates.data');
        Route::get('/{template}/delete', 'Admin\TemplateController@destroy')->name('templates.delete');
        Route::get('/{ContentTemplate}/remove/', 'Admin\TemplateController@removeContentBlock')->name('templates.remove-block');
        Route::post('/sortContent', 'Admin\TemplateController@sortContent')->name('templates.sort-content');
    });
    Route::resource('templates', 'Admin\TemplateController');

    Route::prefix('image-uploader')->group(function () {
        Route::get('/data', 'Admin\ImageController@data')->name('image-uploader.data');
        Route::get('/{image}/delete', 'Admin\ImageController@destroy')->name('image-uploader.delete');
        Route::get('/picture-manager/', 'Admin\ImageController@selectImage')->name('images.picture-manager');
        Route::post('/add-image', 'Admin\ImageController@addImage')->name('images.add-image');
        Route::post('/process-sizes', 'Admin\ImageController@processSizes')->name('images.process-sizes');
        Route::post('/save-crop', 'Admin\ImageController@saveCrop')->name('images.saveCrop');
        Route::post('/upload', 'Admin\ImageController@upload')->name('images.upload');

    });
    Route::resource('image-uploader', 'Admin\ImageController');

    Route::prefix('tags')->group(function () {
        Route::get('/data', 'Admin\TagController@data')->name('tags.data');
        Route::get('/{tag}/delete', 'Admin\TagController@destroy')->name('tags.delete');
    });
    Route::resource('tags', 'Admin\TagController');

    Route::prefix('image-sizes')->group(function () {
        Route::get('/{imageSize}/delete', 'Admin\ImageSizeController@destroy')->name('image-sizes.delete');
    });
    Route::resource('image-sizes', 'Admin\ImageSizeController');

    Route::prefix('blocks')->group(function () {
        Route::get('/data', 'Admin\BlockController@data')->name('blocks.data');
        Route::get('/{block}/delete', 'Admin\BlockController@destroy')->name('blocks.delete');
    });
    Route::resource('blocks', 'Admin\BlockController');

    Route::prefix('content')->group(function () {
        Route::get('/data', 'Admin\ContentController@data')->name('content.data');
        Route::get('/{content}/delete', 'Admin\ContentController@destroy')->name('content.delete');
    });
    Route::resource('content', 'Admin\ContentController');

    Route::prefix('slideshows')->group(function () {
        Route::get('/data', 'Admin\SlideshowController@data')->name('slideshows.data');
        Route::get('/{slideshow}/delete', 'Admin\SlideshowController@destroy')->name('slideshows.delete');
        Route::get('/{slideshow}/add-slides', 'Admin\SlideshowController@addSlides')->name('slideshows.add-slides');
        Route::post('/store-slides', 'Admin\SlideshowController@storeSlides')->name('slideshows.store-slides');
        Route::get('/{slide}/delete-slide', 'Admin\SlideshowController@deleteSlide')->name('slideshows.delete-slide');
        Route::post('/sortSlides', 'Admin\SlideshowController@sortSlides')->name('slideshows.sort-slides');
    });

    Route::resource('slideshows', 'Admin\SlideshowController');

    Route::prefix('permissions')->group(function () {
        Route::get('/data', 'Admin\PermissionController@data')->name('permissions.data');
        Route::get('/{permission}/delete', 'Admin\PermissionController@destroy')->name('permissions.delete');
    });

    Route::resource('permissions', 'Admin\PermissionController');

    Route::prefix('roles')->group(function () {
        Route::get('/data', 'Admin\RoleController@data')->name('roles.data');
        Route::get('/{role}/delete', 'Admin\RoleController@destroy')->name('roles.delete');
    });

    Route::resource('roles', 'Admin\RoleController');

    Route::prefix('applications')->group(function () {
        Route::get('/data', 'Admin\ApplicationController@data')->name('applications.data');
        Route::get('/{application}/delete', 'Admin\ApplicationController@destroy')->name('applications.delete');
        Route::get('/{application}/note', 'Admin\ApplicationController@createNote')->name('applications.note');
        Route::post('/{application}/note', 'Admin\ApplicationController@storeNote');
        Route::get('/note/{applicationNote}/delete', 'Admin\ApplicationController@deleteNote')->name('applications.note.delete');
        Route::get('/note/{applicationNote}', 'Admin\ApplicationController@editNote')->name('applications.note.edit');
        Route::put('/note/{applicationNote}', 'Admin\ApplicationController@updateNote')->name('applications.note.update');
        Route::get('/{application}/pdf','Admin\ApplicationController@printPDF')->name('applications.pdf');
    });

    Route::resource('applications', 'Admin\ApplicationController');

    Route::prefix('contacts')->group(function () {
        Route::get('/data', 'Admin\ContactController@data')->name('contacts.data');
        Route::get('/{contact}/delete', 'Admin\ContactController@destroy')->name('contacts.delete');
    });

    Route::resource('contacts', 'Admin\ContactController');

    Route::prefix('faqs')->group(function () {
        Route::get('/data', 'Admin\FaqController@data')->name('faqs.data');
        Route::get('/{faq}/delete', 'Admin\FaqController@destroy')->name('faqs.delete');
    });

    Route::resource('faqs', 'Admin\FaqController');

    Route::prefix('documents')->group(function () {
//        Route::get('/data', 'Admin\FaqController@data')->name('faqs.data');
        Route::get('/{document}/delete', 'Admin\DocumentController@destroy')->name('documents.delete');
    });
    Route::resource('documents', 'Admin\DocumentController');

    Route::prefix('jobs-admin')->group(function () {
        Route::get('/data', 'Admin\JobController@data')->name('jobs-admin.data');
        Route::get('/{job}/delete', 'Admin\JobController@destroy')->name('jobs-admin.delete');

    });
    Route::resource('jobs-admin', 'Admin\JobController');

    Route::prefix('job-applications')->group(function () {
        Route::get('/data', 'Admin\JobApplicationController@data')->name('job-applications.data');
        Route::get('/{jobApplication}/delete', 'Admin\JobApplicationController@destroy')->name('job-applications.delete');
        Route::get('/{jobApplication}/note', 'Admin\JobApplicationController@createNote')->name('job-applications.note');
        Route::post('/{jobApplication}/note', 'Admin\JobApplicationController@storeNote');
        Route::get('/note/{jobApplicationNote}/delete', 'Admin\JobApplicationController@deleteNote')->name('job-applications.note.delete');
        Route::get('/note/{jobApplicationNote}', 'Admin\JobApplicationController@editNote')->name('job-applications.note.edit');
        Route::put('/note/{jobApplicationNote}', 'Admin\JobApplicationController@updateNote')->name('job-applications.note.update');
        Route::get('/{jobApplication}/pdf','Admin\JobApplicationController@printPDF')->name('job-applications.pdf');

    });
    Route::resource('job-applications', 'Admin\JobApplicationController');

    Route::prefix('appeals')->group(function () {
        Route::get('/data', 'Admin\AppealController@data')->name('appeals.data');
    });
    Route::resource('appeals', 'Admin\AppealController');

    Route::prefix('api')->group(function () {
        Route::get('/data', 'Admin\EvergivingAPIController@data')->name('api.data');
        Route::get('/{evergivingApi}/delete', 'Admin\EvergivingAPIController@destroy')->name('api.delete');
        Route::get('/test', 'Admin\EvergivingAPIController@test')->name('api.test');

    });
    Route::resource('api', 'Admin\EvergivingAPIController');



});

// front routes
Route::get('/application', 'Front\ApplicationController@index')->name('application');
Route::post('/application', 'Front\ApplicationController@process')->name('process');
Route::get('/contact', 'Front\ContactController@index')->name('contact');
Route::post('/contact', 'Front\ContactController@process')->name('contact-process');
Route::get('/jobs', 'Front\JobController@index')->name('job');
Route::get('/jobs/application', 'Front\JobController@create')->name('job.apply');
Route::post('/jobs/application', 'Front\JobController@store')->name('job.process');

resources/views/admin/evergiving/create.blade.php
@extends('admin.layouts.dashboard')

@section('content')
    {{ Form::open(['url' => 'admin/api'])  }}

    <div class="box">
        <div class="box-header">
            Evergiving API Details
        </div>
        <div class="box-content">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        {{ Form::label('api_key', 'API Key')  }}
                        {{ Form::text('api_key', old('api_key'), ['class' => 'form-control'])  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('campaign_id', 'Campaign ID')  }}
                        {{ Form::text('campaign_id', old('campaign_id'), ['class' => 'form-control'])  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('schema_id', 'Schema ID')  }}
                        {{ Form::text('schema_id',old('schema_id'), ['class' => 'form-control'])  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('type', 'Type')  }}
                        {{ Form::select('type',['' => '--- Please Select ---', 'contact' => 'Contact', 'pledge' => 'Pledge'], old('type'), ['class' => 'form-control selectpicker'])  }}
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="form-action clearfix">
        <div class="pull-right">
            <a href="{{ route('api.index') }}" class="btn btn-secondary"><i class="fas fa-list"></i> Back to list</a>
            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Create</button>
        </div>
    </div>

    {{ Form::close()  }}

@endsection

resources/views/admin/evergiving/edit.blade.php
@extends('admin.layouts.dashboard')

@section('content')
    {{ Form::model($api, ['route' => ['api.update', $api->id], 'method' => 'PUT'])  }}

    <div class="box">
        <div class="box-header">
            Appeal Details
        </div>
        <div class="box-content">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        {{ Form::label('api_key', 'API Key')  }}
                        {{ Form::text('api_key', $api->api_key, ['class' => 'form-control'])  }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('campaign_id', 'Campaign ID')  }}
                        {{ Form::text('campaign_id', $api->campaign_id, ['class' => 'form-control'])  }}
                    </div>

                    <div class="form-group">
                        {{ Form::label('schema_id', 'Schema ID')  }}
                        {{ Form::text('schema_id', $api->schema_id, ['class' => 'form-control'])  }}
                    </div>
                    <div class="form-group">
                        {{ Form::label('type', 'Type')  }}
                        {{ Form::select('type',['' => '--- Please Select ---', 'contact' => 'Contact', 'pledge' => 'Pledge'],$api->type, ['class' => 'form-control selectpicker'])  }}

                    </div>

                </div>

            </div>

        </div>
    </div>

    <div class="form-action clearfix">
        <div class="pull-right">
            <a href="{{ route('api.index') }}" class="btn btn-secondary"><i class="fas fa-list"></i> Back to list</a>
            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Save</button>

        </div>
    </div>
    {{ Form::close()  }}

@endsection

resources/views/admin/evergiving/index.blade.php
@extends('admin.layouts.dashboard')

@section('content')

    <div class="box">
        <div class="box-header">
            <div class="box-buttons">
                <a href="{{ route('api.create') }}" data-toggle="tooltip" title="" class="box-btn tooltip-pivot" data-original-title="Add"><i class="fas fa-plus"></i></a>
            </div>
            Evergiving API's

        </div>
        <div class="box-content">
            <table class="table table-bordered" id="api-table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>API Key (first 10 digits)</th>
                    <th>Campaign ID</th>
                    <th>Schema ID</th>
                    <th>Type</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>

    <a class="btn btn-success pull-right" href="{{ route('api.create')  }}" class="btn btn-success"><i class="fas fa-plus"></i> Add Evergiving API</a>

@stop

@section('scripts')
    <script>
        $(function() {
            $.noConflict(true)
            var oTable = $('#api-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '{{ route('api.data')  }}'
                },
                order: [[ 1, "asc" ]],
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'api_key', name: 'api_key' },
                    { data: 'campaign_id', name: 'campaign_id' },
                    { data: 'schema_id', name: 'schema_id' },
                    { data: 'type', name: 'type' },
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
            });

        });

    </script>
@stop

resources/views/admin/evergiving/view.blade.php
@extends('admin.layouts.dashboard')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    Evergiving API Details
                </div>

                <div class="box-content">
                    <div class="row">
                        <div class="col-md-8">
                            <dl class="dl-horizontal" >
                                <dt>API Key</dt>
                                <dd>{{ $apiKey }}</dd>
                                <dt>Campaign ID</dt>
                                <dd>{{ $api->campaign_id }}</dd>
                                <dt>Schema ID</dt>
                                <dd>{{ $api->schema_id }}</dd>
                                <dt>Type</dt>
                                <dd>{{ ucfirst($api->type)}}</dd>
                                <dt>Revision ID</dt>
                                <dd>{{ $api->revision_id}}</dd>
                            </dl>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="form-action clearfix">
        <div class="pull-right">
            <a href="{{ route('api.index') }}" class="btn btn-secondary"><i class="fas fa-bars"></i> Back to list</a>
            @can('Edit Evergiving API')
                <a href="{{ route('api.edit', $api->id) }}" class="btn btn-primary"><i class="fas fa-pencil-alt "></i> Edit</a>
            @endcan
        </div>
    </div>
@stop